/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App

fun main(){
    trocaValor()
    area()
}

fun trocaValor() {
    var a: String = "a"
    var b: String = "b"

    println("A = $a\nB = $b")

    val c: String = a
    a = b
    b = c

    println("A = $a\nB = $b")
}

fun area(){
    print("Digite o valor do raio: ")
    val raio = readLine()!!.toDouble()
    val pi : Double =  3.14159265

    val area: Double = (raio * raio) * pi

    println("Area : $area")
}